// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnqIsQUaQV5vAyyfqrH8E9raZu56Dv-QU',
    appId: '1:670755970626:web:d0ef762fcee27742f8d7db',
    messagingSenderId: '670755970626',
    projectId: 'md-cool-project',
    authDomain: 'md-cool-project.firebaseapp.com',
    storageBucket: 'md-cool-project.appspot.com',
    measurementId: 'G-QGKF39X11C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-ftoncjRrso0gwIxqSql58JYFxUqg47o',
    appId: '1:670755970626:android:2b4414f4bf3e7486f8d7db',
    messagingSenderId: '670755970626',
    projectId: 'md-cool-project',
    storageBucket: 'md-cool-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW0p0ZOrAGGEgRmNDZK1e4zOxO5an6jd4',
    appId: '1:670755970626:ios:1cad1bd5cd9c1bcef8d7db',
    messagingSenderId: '670755970626',
    projectId: 'md-cool-project',
    storageBucket: 'md-cool-project.appspot.com',
    iosClientId: '670755970626-gq6fv7jckvonq8qe1vro1b1a210qhie8.apps.googleusercontent.com',
    iosBundleId: 'com.example.mdapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW0p0ZOrAGGEgRmNDZK1e4zOxO5an6jd4',
    appId: '1:670755970626:ios:1cad1bd5cd9c1bcef8d7db',
    messagingSenderId: '670755970626',
    projectId: 'md-cool-project',
    storageBucket: 'md-cool-project.appspot.com',
    iosClientId: '670755970626-gq6fv7jckvonq8qe1vro1b1a210qhie8.apps.googleusercontent.com',
    iosBundleId: 'com.example.mdapp',
  );
}
